language:
    - cpp
dist:
    - trusty
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
install:
    - sudo apt-get install -y autoconf-archive
    - sudo apt-get install -y libboost-all-dev
    - sudo apt-get install -y cpputest
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
before_script:
    - autoconf --version
    - automake --version
script:
    - autoreconf --install
    - ./configure
    - make V=1 -j4 clean all
after_success:
    - ./demo-cpputest -c
